### PR TITLE
[Fix] Census employee first name missing bug

### LINKED ISSUE #219: [Bug] No logic on empty name fields during census upload
happening if name field is blank during employee/data-builder createFullname function at the trim() call

### PR DESCRIPTION
**Pull request by petersonbrock**
closes #219

### CODE REVIEW

File: api/employee/data-builder.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const createFullName = employee => {
       suffix = employee['name.suffix'] || employee.suffix,
       fullName = '';
 
-  fullName += first.trim().replace(/[.]/g, '') || '';
+  fullName += first ? first.trim().replace(/[.]/g, '') : '';
```
Comment (James1x0) [inline api/employee/data-builder.js]: A little more succinct 
```suggestion
  fullName += (first || '').trim().replace(/[.]/g, '');
```

File: api/employee/index.js [hunk 2]
```diff
@@ -59,7 +59,7 @@ const createFullName = name => {
       } = name.name || name,
       fullName = '';
 
-  fullName += first.trim().replace(/[.]/g, '') || '';
+  fullName += first ? first.trim().replace(/[.]/g, '') : '';
```
Comment (James1x0) [inline api/employee/index.js]:
```suggestion
  fullName += (first || '').trim().replace(/[.]/g, '');
```
