### PR TITLE
[Bug] Change `isCompleted` to `completedOn` in job applications

### LINKED ISSUE #294: [Enhancement] Change `isCompleted` to `completedOn` in job applications

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #294
close with associatedemployers/quartz#95
close with associatedemployers/granite#740

### CODE REVIEW

File: lib/models/job-application/middleware/properties/complete.js [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
+        moment     = require('moment');
 
   try {
     if (!this.jobOpening) {
       return next();
     }
 
     let { screening } = await JobOpening.findById(this.jobOpening._id || this.jobOpening).populate('screening');
-    this.isCompleted = !screening || this.responses && this.responses.length === screening.elements.length;
+    this.completedOn = !screening || this.responses && this.responses.length === screening.elements.length ? moment() : null;
```
Comment (James1x0) [inline lib/models/job-application/middleware/properties/complete.js]:
```suggestion
    this.completedOn = !screening || this.responses && this.responses.length === screening.elements.length ? new Date() : null;
```

File: lib/models/job-application/middleware/properties/complete.js [hunk 2]
```diff
@@ -1,13 +1,14 @@
 async function middleware (next) {
-  const JobOpening = require('../../../job-opening');
+  const JobOpening = require('../../../job-opening'),
+        moment     = require('moment');
```
Comment (James1x0) [inline lib/models/job-application/middleware/properties/complete.js]:
```suggestion
```

File: lib/models/job-application/middleware/properties/complete.js [hunk 3]
```diff
@@ -1,13 +1,14 @@
 async function middleware (next) {
-  const JobOpening = require('../../../job-opening');
+  const JobOpening = require('../../../job-opening'),
```
Comment (James1x0) [inline lib/models/job-application/middleware/properties/complete.js]:
```suggestion
  const JobOpening = require('../../../job-opening');
```

File: lib/models/job-application/index.js [hunk 4]
```diff
@@ -73,7 +73,7 @@ var jobApplicationSchema = new Schema({
   disqualificationEmail:  Boolean,
   publicLink:             String,
 
-  isCompleted: Boolean,
+  completedOn: Date,
```
Comment (James1x0) [inline lib/models/job-application/index.js]: Additionally, since this property is changing, we need to migrate all of HEI's applications over to the new prop.

Comment (JavaLavaMT) [reply lib/models/job-application/index.js]: 🏁
