### PR TITLE
[Fix] Census timezone issue

### LINKED ISSUE #228: [Bug] Census upload dates were off
> The imported dates are wrong..  Birthdays are one day greater and hire dates are one day less. Birthdays are one day less, not greater
Cyndi

Possibly a TZ issue on the box?

### PR DESCRIPTION
**Pull request by petersonbrock**
closes #228 

uses moment timezone to account for company's timezone when saving dates through census.

moment.tz does not work accurately if not passed a date in 'YYYY-MM-DD' format

### CODE REVIEW

File: api/employee/data-builder.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ const instanceConverters = {
   String:  v => toString(v),
   Number:  v => toNumber(v),
   Boolean: v => v === 'TRUE' ? true : false,
-  Date:    v => moment(v, 'M/D/YYYY').toISOString()
+  Date:    (v, tz) => moment.tz(moment(v, 'M/D/YYYY').format('YYYY-MM-DD'), tz)
```
Comment (James1x0) [inline api/employee/data-builder.js]: Doesn't this just return a moment object? We should probably be returning an ISO string so mongoose can read this properly...

Screen Shot 2019-09-18 at 7 56 31 AM
