### PR TITLE
[Fix] Orphaned Job Apps in Pipeline

### LINKED ISSUE #257: [Bug] Orphaned application when pipeline stage removed

### PR DESCRIPTION
**Pull request by petersonbrock**
closes #257

### CODE REVIEW

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
+const { map } = require('lodash');
+
+module.exports = event => {
+  return async function (pipeline, next) {
+    let JobApplication = require('../../models/job-application'),
+        Pipeline = require('../../models/recruiting-pipeline'),
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]: These should be `const`, others `let`

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        //find apps with a stage that doesnt match current pipeline stages
+        //if event is removal, we know the entire array of jobOpenings are orphans, no need to query for stages
+        jobApplicationQuery.stage = { $nin: map(pipeline.stages, '_id') };
+      }
+    }
+
+    let orphanedApplications = await JobApplication.find(jobApplicationQuery);
+
+    if (orphanedApplications.length < 1) {
+      next();
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]:
```suggestion
      return next();
```
Right? Otherwise, it'll run the rest of this code.

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+    }
+
+    let defaultStages = (await Pipeline.find({
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]:
```suggestion
    const defaultStages = (await Pipeline.find({
```

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    if (event === 'save') {
+      //if event is save, pipeline = pipeline after saving
+      //use company default stages as previous stages if transitioning from default to custom pipeline
+      previousStages = pipeline.stagesWas || defaultStages;
+      currentStages = pipeline.stages;
+    } else if (event === 'remove') {
+      //if event is remove, pipeline = pipeline previous to removal
+      previousStages = pipeline.stages;
+      currentStages = defaultStages;
+    }
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]: I believe we can simply these lines.
```suggestion
    previousStages = event === 'save' ? (pipeline.stagesWas || defaultStages) : pipeline.stages;
    currentStages = event === 'save' ? pipeline.stages : defaultStages
```

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+        return;
+      }
+
+      let matchingStage = currentStages.find(({ name }) => name.toLowerCase() === previousStage.name.toLowerCase());
+
+      if (matchingStage) {
+        app.stage = matchingStage._id;
+      } else {
+        app.stage = currentStages[0]._id;
+      }
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]:
```suggestion
      app.stage = (matchingStage || {})._id || currentStages[0]._id;
```

File: lib/models/recruiting-pipeline/restage-orphaned-job-applications.js [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+      app.save();
```
Comment (James1x0) [inline lib/models/recruiting-pipeline/restage-orphaned-job-applications.js]: Does this need to be awaited? If so you may need to convert this into a for loop
