### PR TITLE
[Bug] Liking an activity item caused employee name to disappear

### LINKED ISSUE #245: [Bug] Liking an activity item caused employee name to disappear

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #245

### CODE REVIEW

File: lib/models/activity/index.js [hunk 1]
```diff
@@ -86,4 +86,6 @@ activitySchema.virtual('humanizedTargetType').get(function () {
   return inflect.humanize(inflect.underscore(this.constructor.modelName)).toLowerCase();
 });
 
+activitySchema.plugin(require('../plugins/was-new'));
```
Comment (James1x0) [inline lib/models/activity/index.js]: You don't need was-new for model#isNew
