### PR TITLE
[Bug] Normalization for phone is weird w/ slate sync

### LINKED ISSUE #263: [Bug] Normalization for phone is weird w/ slate sync
We may have to add this to transforms: (and vice-versa on slate's transforms)
```javascript
  phone: {
    toKey: 'phone',
    normalize (v) {
      return v ? v.replace(/\D/g, '').replace(/\d?(\d{3})(\d{3})(\d{4})/, '$1-$2-$3') : v;
    }
  }
```

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #263

### CODE REVIEW

File: lib/integrations/slate/config/transforms/definitions.js [hunk 1]
```diff
@@ -5,6 +5,14 @@ exports.employees = {
       obj.payRate = obj.payRate.hourly || obj.payRate.salary;
     }
 
+    if (obj.phone) {
+      obj.phone.replace(/\D/g, '').replace(/\d?(\d{3})(\d{3})(\d{4})/, '($1) $2-$3');
+    }
+
+    if (obj.ssn) {
+      obj.ssn.replace(/\D/g, '').replace(/\d?(\d{3})(\d{2})(\d{4})/, '$1$2$3');
```
Comment (James1x0) [inline lib/integrations/slate/config/transforms/definitions.js]: Seems superfluous.
```suggestion
      obj.ssn.replace(/\D/g, '');
```

File: lib/integrations/slate/config/transforms/definitions.js [hunk 2]
```diff
@@ -17,6 +25,14 @@ exports.employees = {
       };
     }
 
+    if (obj.phone) {
+      obj.phone.replace(/\D/g, '').replace(/\d?(\d{3})(\d{3})(\d{4})/, '$1$2$3');
```
Comment (James1x0) [inline lib/integrations/slate/config/transforms/definitions.js]: And again.
```suggestion
      obj.phone.replace(/\D/g, '');
```
